#!/usr/bin/python3
# COMP3311 20T2 Final Exam
# Q7: tracklist for album, given by Albums.id
#     show performers/instruments for each track

import sys
import psycopg2

# ... put helper functions here ...
def getAlbum(id):
   cur = db.cursor()
   qry = '''
   select *
   from albums
   where id = %s
   '''
   cur.execute(qry,[id])
   info = cur.fetchone()
   cur.close()
   
   if not info:
      return None
   else:
      return info

def getAlbumSongs(id):
   cur = db.cursor()
   qry = '''
   select *
   from songs
   where on_album = %s
   '''
   cur.execute(qry,[id])
   info = cur.fetchall()
   cur.close()
   
   if not info:
      return None
   else:
      return info

def getSongPerformers(id):
   cur = db.cursor()
   qry = '''
   select *, p.name
   from playson po
      join songs s on s.id = po.song
      join performers p on po.performer = p.id
   where s.id = %s
   order by p.name
   '''
   cur.execute(qry,[id])
   info = cur.fetchall()
   cur.close()
   
   if not info:
      return None
   else:
      return info

db = None
cur = None
usage = f"Usage: {sys.argv[0]} AlbumID"

# process command-line args

if len(sys.argv) < 2:
   print(usage)
   exit(1)
albumID = sys.argv[1]
if not albumID.isnumeric():
   print(usage)
   exit(1)

try:
   db = psycopg2.connect("dbname=music")

   # ... your code goes here ...
   album = getAlbum(albumID)

   if album is None:
      print("Invalid album ID")
      exit()

   # print(album)
   name = album[1]
   year = album[2]
   genre = album[4]

   print(f"{name} ({year}) ({genre})")
   print("========================================")

   songs = getAlbumSongs(albumID)
   
   trackno = 1
   for song in songs:
      print(song)
      songID = song[0]
      title = song[1]
      print(f"%2d. %s" %(trackno, title))

      performers = getSongPerformers(songID)
      if performers is None:
         print("The whole group")
         trackno += 1
         continue

      for performer in performers:
         performerName = performer[9]
         instruments = performer[2]
         print(instruments)
         # print(f"%8s%s: %s" %(name, instruments))
      # print(f"%2d. %s (%d:%02d)" %(trackno, title, minutes, seconds))

      trackno += 1



except psycopg2.Error as err:
   print("DB error: ", err)
finally:
   if cur:
       cur.close()
   if db:
      db.close()

